# Gurbir Arora
# 105178554
# gurbthebruin@g.ucla.edu

default: dist

dist: README
	tar -czvf lab4a-105178554.tar.gz my_beaglebone.jpg connected.png copy.png build_run.png git.png README Makefile

clean: 
	rm -f *.tar.gz
