# Gurbir Arora
# 105178554
# gurbthebruin@g.ucla.edu

default: lab1a.c
	gcc -o lab1a -g -Wall -Wextra lab1a.c

clean: 
	rm -f lab1a lab1a-105178554.tar.gz

dist: lab1a.c Makefile README
	tar -cvzf lab1a-105178554.tar.gz lab1a.c README Makefile
